### ISSUE TITLE
Add X icon to change old Twitter icon

### ISSUE THREAD

**Issue by Nat-SB** [Pictogrammers/Memory#12]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Pictogrammers/Memory/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/memory) to make sure the icon doesn't already exist.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

People can use it to change the old Twitter logo to the new one.

### Give us an example of what this icon might look like.

![Screenshot 2024-01-03 at 15 23 25](https://github.com/Pictogrammers/Memory/assets/125361038/64a2b3dc-18fb-41dc-b8f3-58097afeab20)
![Screenshot 2024-01-03 at 15 25 04](https://github.com/Pictogrammers/Memory/assets/125361038/dfa619b6-d90c-479a-9f2d-a069427f00ca)

**Comment by Templarian** [comment]
Wrong repo.
