### ISSUE TITLE
beer

### ISSUE THREAD

**Issue by Templarian** [Pictogrammers/Memory#2]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Pictogrammers/Memory/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/memory) to make sure the icon doesn't already exist.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Depicting a beer. Beer mug.

### Give us an example of what this icon might look like.

N/A.

**Comment by MaxBittker** [comment]
wanted to hop onto this issue to say thank you for the whole project, it's super cool.

**Comment by Templarian** [comment]
@MaxBittker Glad to hear you like the project. If you haven't seen the font that complements this icon pack called called Jun definitely check that out also. We are still building out the Pictogrammers' site to support fonts. Right now Jun only has a monospace, but we'll be working on the Sans Serif version shortly.

https://pictogrammers.github.io/@pictogrammers/jun/
