### ISSUE TITLE
Flipper Zero

### ISSUE THREAD

**Issue by Atomofiron** [Pictogrammers/Memory#4]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Pictogrammers/Memory/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/memory) to make sure the icon doesn't already exist.

### Tell us about your contribution.

This icon can indicate something related to the device called Flipper Zero (google it please). For example a chapter or app functions interacting with Flipper Zero directly. Little example here atomofiron.github.io

### Share a preview of your contribution.

preview is scaled, original size is 22x48 (2 points per side insets included)

<img width="361" alt="flipper-zero-preview" src="https://github.com/Pictogrammers/Memory/assets/14147217/412fd00e-84f2-45bf-92bc-acc3ed5a7f35">

### Upload the icon source.

[flipper-zero.svg.zip](https://github.com/Pictogrammers/Memory/files/12198519/flipper-zero.svg.zip)

**Comment by Templarian** [comment]
@Atomofiron Looks nice (my buddy has one, so played with it a little bit). Unfortunately the Memory Icon set is primarily aimed at more generalized / gaming icons.
